-- Valores aplicados com SetVisualSettingFloat enquanto o resource está ligado.
-- restore é o conjunto usado ao parar o resource. O jogo não grava isso em disco:
-- fechar o FiveM recarrega o visualsettings.dat original dos arquivos do jogo.
-- Nenhuma chave aqui substitui um arquivo da instalação.

GraphicsVisualSettings = {
    restore = {
        ['car.headlights.global.HeadlightIntensityMult'] = 1.0,
        ['car.headlights.global.HeadlightDistMult'] = 1.0,
        ['car.headlights.fullbeam.IntensityMult'] = 1.0,
        ['car.headlights.fullbeam.DistMult'] = 1.0,
        ['car.headlights.fullbeam.CoronaIntensityMult'] = 1.0,
        ['car.headlights.fullbeam.CoronaSizeMult'] = 1.0,
        ['car.headlight.night.emissive.on'] = 10.0,
        ['car.headlight.day.emissive.on'] = 10.0,
        ['misc.coronas.sizeScaleGlobal'] = 0.5,
        ['misc.coronas.intensityScaleGlobal'] = 0.5,
        ['bloom.threshold.min'] = 0.4,
        ['bloom.blurblendmult.large'] = 0.5,
        ['bloom.blurblendmult.med'] = 1.0,
        ['bloom.blurblendmult.small'] = 0.5,
        ['puddles.scale'] = 0.015,
        ['puddles.strength'] = 0.5,
        ['puddles.depth'] = 0.9,
        ['puddles.ripples.ripplestrength'] = 0.7,
        ['distantlights.size'] = 0.8,
        ['distantlights.streetlight.HDRIntensity'] = 15.0,
        ['distantlights.carlight.HDRIntensity'] = 5.0,
        ['reflection.tweaks.exterior.artificial.boost'] = 3.0,
        ['reflection.tweaks.emissive.boost'] = 5.0,
        ['rain.fadeInScale'] = 2.0,
        ['rain.NumberParticles'] = 16384.0,
    },

    profiles = {
        quality = {
            base = {
                ['car.headlights.global.HeadlightIntensityMult'] = 2.1,
                ['car.headlights.global.HeadlightDistMult'] = 1.7,
                ['car.headlights.fullbeam.IntensityMult'] = 1.15,
                ['car.headlights.fullbeam.DistMult'] = 1.8,
                ['car.headlights.fullbeam.CoronaIntensityMult'] = 1.05,
                ['car.headlights.fullbeam.CoronaSizeMult'] = 1.15,
                ['car.headlight.night.emissive.on'] = 16.0,
                ['car.headlight.day.emissive.on'] = 12.0,
                ['misc.coronas.sizeScaleGlobal'] = 0.62,
                ['misc.coronas.intensityScaleGlobal'] = 0.58,
                ['bloom.threshold.min'] = 0.64,
                ['bloom.blurblendmult.large'] = 0.32,
                ['bloom.blurblendmult.med'] = 0.8,
                ['bloom.blurblendmult.small'] = 0.4,
                ['puddles.scale'] = 0.012,
                ['puddles.strength'] = 0.45,
                ['puddles.depth'] = 0.8,
                ['puddles.ripples.ripplestrength'] = 0.55,
                ['distantlights.size'] = 0.9,
                ['distantlights.streetlight.HDRIntensity'] = 13.5,
                ['distantlights.carlight.HDRIntensity'] = 6.5,
                ['reflection.tweaks.exterior.artificial.boost'] = 4.2,
                ['reflection.tweaks.emissive.boost'] = 6.0,
                ['rain.fadeInScale'] = 1.6,
                ['rain.NumberParticles'] = 18432.0,
            },
            rain = {
                ['car.headlights.global.HeadlightIntensityMult'] = 2.4,
                ['misc.coronas.intensityScaleGlobal'] = 0.50,
                ['puddles.scale'] = 0.046,
                ['puddles.strength'] = 0.95,
                ['puddles.depth'] = 1.35,
                ['puddles.ripples.ripplestrength'] = 1.05,
                ['reflection.tweaks.exterior.artificial.boost'] = 6.5,
                ['reflection.tweaks.emissive.boost'] = 7.5,
                ['rain.fadeInScale'] = 1.15,
                ['rain.NumberParticles'] = 22000.0,
            },
        },
        performance = {
            base = {
                ['car.headlights.global.HeadlightIntensityMult'] = 1.45,
                ['car.headlights.global.HeadlightDistMult'] = 1.15,
                ['car.headlights.fullbeam.IntensityMult'] = 1.0,
                ['car.headlights.fullbeam.DistMult'] = 1.2,
                ['car.headlights.fullbeam.CoronaIntensityMult'] = 0.9,
                ['car.headlights.fullbeam.CoronaSizeMult'] = 0.95,
                ['car.headlight.night.emissive.on'] = 12.0,
                ['car.headlight.day.emissive.on'] = 10.0,
                ['misc.coronas.sizeScaleGlobal'] = 0.48,
                ['misc.coronas.intensityScaleGlobal'] = 0.42,
                ['bloom.threshold.min'] = 0.78,
                ['bloom.blurblendmult.large'] = 0.22,
                ['bloom.blurblendmult.med'] = 0.55,
                ['bloom.blurblendmult.small'] = 0.3,
                ['puddles.scale'] = 0.010,
                ['puddles.strength'] = 0.35,
                ['puddles.depth'] = 0.6,
                ['puddles.ripples.ripplestrength'] = 0.4,
                ['distantlights.size'] = 0.7,
                ['distantlights.streetlight.HDRIntensity'] = 11.0,
                ['distantlights.carlight.HDRIntensity'] = 4.5,
                ['reflection.tweaks.exterior.artificial.boost'] = 2.6,
                ['reflection.tweaks.emissive.boost'] = 4.0,
                ['rain.fadeInScale'] = 2.0,
                ['rain.NumberParticles'] = 12288.0,
            },
            rain = {
                ['puddles.scale'] = 0.024,
                ['puddles.strength'] = 0.60,
                ['puddles.depth'] = 0.85,
                ['puddles.ripples.ripplestrength'] = 0.6,
                ['reflection.tweaks.exterior.artificial.boost'] = 3.2,
                ['rain.NumberParticles'] = 14000.0,
            },
        },
    },
}
